from __future__ import annotations

from typing import Any, Sequence
from uuid import UUID

from sqlalchemy.orm import Session

from app.models.chat import Message
from app.models.chunk import Chunk
from app.models.citation import Citation
from app.models.document import Document


class CitationPersistenceService:
    """
    Step 8 PostgreSQL citation persistence.

    Converts citations generated by CitationAgent into rows
    in the existing PostgreSQL `citations` table.

    Security / provenance guarantees
    --------------------------------
    A generated citation is accepted only when:

        1. citation.evidence_id exists in retrieved evidence
        2. that evidence contains postgres_chunk_id
        3. the PostgreSQL Chunk actually exists
        4. the Chunk's Document belongs to the same user
           as the assistant Message's Chat

    This ensures citations never point to:

        - invented chunks
        - stale Chroma-only vectors
        - another user's document
    """

    def __init__(
        self,
        db: Session,
    ):
        self.db = db

    # =========================================================
    # PUBLIC
    # =========================================================

    def persist_citations(
        self,
        *,
        message: Message,
        generated_citations: Sequence[
            dict[str, Any]
        ],
        evidence: Sequence[
            dict[str, Any]
        ],
        replace_existing: bool = True,
        strict: bool = True,
        commit: bool = True,
    ) -> list[Citation]:
        """
        Persist CitationAgent citations for one assistant message.

        Parameters
        ----------
        message:
            PostgreSQL assistant Message.

        generated_citations:
            CitationAgent output.

        evidence:
            Step 7 PostgreSQL-verified evidence.

        replace_existing:
            Delete previous citations for this message before
            inserting new ones.

        strict:
            When True, every generated citation must map to a
            valid PostgreSQL Chunk.

        commit:
            Commit immediately when True.

            AgenticRAGService passes False so messages and
            citations can be committed atomically.
        """

        if message is None:
            raise ValueError(
                "message is required."
            )

        if message.id is None:
            raise ValueError(
                "message must be flushed before "
                "citations can be persisted."
            )

        if message.role != "assistant":
            raise ValueError(
                "Citations can only be attached "
                "to assistant messages."
            )

        try:

            if replace_existing:

                (
                    self.db.query(Citation)
                    .filter(
                        Citation.message_id
                        == message.id
                    )
                    .delete(
                        synchronize_session=False
                    )
                )

            evidence_lookup = (
                self._build_evidence_lookup(
                    evidence
                )
            )

            stored: list[Citation] = []

            seen_chunk_ids: set[
                UUID
            ] = set()

            for generated in generated_citations:

                if not isinstance(
                    generated,
                    dict,
                ):
                    continue

                evidence_id = str(
                    generated.get(
                        "evidence_id",
                        "",
                    )
                ).strip()

                source_evidence = (
                    evidence_lookup.get(
                        evidence_id
                    )
                )

                if source_evidence is None:

                    if strict:
                        raise ValueError(
                            "Generated citation references "
                            f"unknown evidence_id: "
                            f"{evidence_id}"
                        )

                    continue

                postgres_chunk_id = (
                    source_evidence.get(
                        "postgres_chunk_id"
                    )
                    or (
                        source_evidence.get(
                            "metadata",
                            {}
                        )
                        or {}
                    ).get(
                        "postgres_chunk_id"
                    )
                )

                if not postgres_chunk_id:

                    if strict:
                        raise ValueError(
                            "Verified evidence does not "
                            "contain postgres_chunk_id."
                        )

                    continue

                chunk_uuid = (
                    self._parse_uuid(
                        postgres_chunk_id,
                        field_name=(
                            "postgres_chunk_id"
                        ),
                    )
                )

                # Avoid duplicate DB citations to the same
                # PostgreSQL chunk.
                if chunk_uuid in seen_chunk_ids:
                    continue

                chunk = (
                    self._authorized_chunk(
                        chunk_id=chunk_uuid,
                        message=message,
                    )
                )

                if chunk is None:

                    if strict:
                        raise PermissionError(
                            "Citation chunk does not exist "
                            "or does not belong to the "
                            "message owner."
                        )

                    continue

                metadata = (
                    source_evidence.get(
                        "metadata",
                        {}
                    )
                    or {}
                )

                page_number = (
                    metadata.get(
                        "page_number"
                    )
                )

                if page_number is None:
                    page_number = (
                        chunk.page_number
                    )

                if page_number is not None:

                    try:
                        page_number = int(
                            page_number
                        )
                    except (
                        TypeError,
                        ValueError,
                    ):
                        page_number = (
                            chunk.page_number
                        )

                relevance_score = (
                    source_evidence.get(
                        "relevance_score"
                    )
                )

                if relevance_score is not None:

                    try:

                        relevance_score = float(
                            relevance_score
                        )

                    except (
                        TypeError,
                        ValueError,
                    ):

                        relevance_score = None

                quoted_text = str(
                    source_evidence.get(
                        "content",
                        "",
                    )
                ).strip()

                citation = Citation(
                    message_id=message.id,
                    chunk_id=chunk.id,
                    page_number=page_number,
                    relevance_score=(
                        relevance_score
                    ),
                    quoted_text=(
                        quoted_text
                        or None
                    ),
                )

                self.db.add(
                    citation
                )

                stored.append(
                    citation
                )

                seen_chunk_ids.add(
                    chunk_uuid
                )

            # Generates UUIDs without committing the larger
            # AgenticRAG transaction.
            self.db.flush()

            if commit:

                self.db.commit()

                for citation in stored:
                    self.db.refresh(
                        citation
                    )

            return stored

        except Exception:

            if commit:
                self.db.rollback()

            raise

    # =========================================================
    # READ
    # =========================================================

    def get_message_citations(
        self,
        message_id: UUID | str,
    ) -> list[Citation]:

        message_uuid = (
            self._parse_uuid(
                message_id,
                field_name="message_id",
            )
        )

        return (
            self.db.query(Citation)
            .filter(
                Citation.message_id
                == message_uuid
            )
            .order_by(
                Citation.created_at.asc()
            )
            .all()
        )

    def count_message_citations(
        self,
        message_id: UUID | str,
    ) -> int:

        message_uuid = (
            self._parse_uuid(
                message_id,
                field_name="message_id",
            )
        )

        return (
            self.db.query(Citation)
            .filter(
                Citation.message_id
                == message_uuid
            )
            .count()
        )

    # =========================================================
    # EVIDENCE LOOKUP
    # =========================================================

    @staticmethod
    def _build_evidence_lookup(
        evidence: Sequence[
            dict[str, Any]
        ],
    ) -> dict[
        str,
        dict[str, Any],
    ]:

        lookup: dict[
            str,
            dict[str, Any],
        ] = {}

        for item in evidence:

            if not isinstance(
                item,
                dict,
            ):
                continue

            evidence_id = str(
                item.get(
                    "chunk_id",
                    "",
                )
            ).strip()

            if evidence_id:
                lookup[
                    evidence_id
                ] = item

        return lookup

    # =========================================================
    # AUTHORIZED CHUNK
    # =========================================================

    def _authorized_chunk(
        self,
        *,
        chunk_id: UUID,
        message: Message,
    ) -> Chunk | None:
        """
        Verify the citation Chunk belongs to the same user
        that owns the Message's Chat.
        """

        chat = message.chat

        if chat is None:
            return None

        return (
            self.db.query(Chunk)
            .join(
                Document,
                Chunk.document_id
                == Document.id,
            )
            .filter(
                Chunk.id == chunk_id,
                Document.owner_id
                == chat.user_id,
            )
            .first()
        )

    # =========================================================
    # SERIALIZE
    # =========================================================

    @staticmethod
    def to_dict(
        citation: Citation,
    ) -> dict[str, Any]:

        return {
            "id": str(
                citation.id
            ),
            "message_id": str(
                citation.message_id
            ),
            "chunk_id": str(
                citation.chunk_id
            ),
            "page_number": (
                citation.page_number
            ),
            "relevance_score": (
                citation.relevance_score
            ),
            "quoted_text": (
                citation.quoted_text
            ),
        }

    # =========================================================
    # UUID
    # =========================================================

    @staticmethod
    def _parse_uuid(
        value: UUID | str,
        *,
        field_name: str,
    ) -> UUID:

        if isinstance(
            value,
            UUID,
        ):
            return value

        try:

            return UUID(
                str(value)
            )

        except (
            ValueError,
            TypeError,
            AttributeError,
        ) as exc:

            raise ValueError(
                f"{field_name} must be "
                "a valid UUID."
            ) from exc